### ISSUE TITLE
Remove jcenter() dependency

### ISSUE THREAD

**Issue by ahetawal-p** [mattermoran/map_launcher#100]
It seems Android deps are still being fetched from `jcenter()` https://github.com/mattermoran/map_launcher/blob/master/android/build.gradle#L20

Which seems to be unreliable, as most of CI builds fail due to 502 bad gateway while fetching the dependencies.
Would be great if this can be moved to `mavenCentral`.

**Comment by mattermoran** [comment]
Ohhh right right haven't updated in a while. Will do that today :)

**Comment by mattermoran** [comment]
Fixed in 2.1.2 :)
