### ISSUE TITLE
App crush using this framework

### ISSUE THREAD

**Issue by yeminsoe** [mattermoran/map_launcher#104]
When I open using this package, My app was crush. How should I solve it? But it is okay in Android, it is not okay in iOS

**Comment by mattermoran** [comment]
It's hard to say what's causing the crash.
- What version of flutter?
- Did you follow the installation steps?
- When does it fail? When you just open the app or when you try to use methods from the package?

**Comment by yeminsoe** [comment]
Unexpectedly found nil while unwrapping an Optional value: file map_launcher/SwiftMapLauncherPlugin.swift, line 61

**Comment by mattermoran** [comment]
this is not helping much. Can you answer the questions above? At which point does it fail? What method you are using, etc? I need more details

**Comment by mattermoran** [comment]
Closing as I was not provided enough info to investigate.
Please reopen with more info and steps to reproduce
