### ISSUE TITLE
Cannot find destination on GoogleMaps

### ISSUE THREAD

**Issue by filipwis** [mattermoran/map_launcher#105]
await MapLauncher.showMarker(
                mapType: MapType.google,
                coords: Coords(7.759392, -122.5107336),
                title: '',
                description: '',
)

GoogleMaps adds parentheses on the end of the coordinates 
![image](https://user-images.githubusercontent.com/60195539/153189710-8e942ad6-4932-41fb-9234-db3653ba55b9.png)

**Comment by sovoereign** [comment]
@filipwis did you find the solution, still facing with latest version?
