### ISSUE TITLE
map_launcher doesnt work with recent version of flutter

### ISSUE THREAD

**Issue by kashlo** [mattermoran/map_launcher#107]
map_launcher causes Flutter project build error

 /Users/user/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.2.1+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (96, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

> Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision db747aa133 (6 days ago) • 2022-02-09 13:57:35 -0600
> Engine • revision ab46186b24
> Tools • Dart 2.16.1 • DevTools 2.9.2
>

**Comment by mattermoran** [comment]
I just tried to create a new flutter project and add map_launcher as a dependency and there's no issue. Looks like there's a mismatch in kotlin version. Did you try to run `flutter clean` and try again?

**Comment by tigloo** [comment]
Same thing happened for us when upgrading an existing project from Flutter 2.8.1 to Flutter 2.10.1. We could fix it by upgrading the Kotlin Gradle plugin version:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/2720850/154260529-ca83b39e-f75a-4101-8baa-c8c1e24b7fdf.png">

Perform the change in android/build.gradle

**Comment by kashlo** [comment]
> I just tried to create a new flutter project and add map_launcher as a dependency and there's no issue. Looks like there's a mismatch in kotlin version. Did you try to run `flutter clean` and try again?

running `flutter clean` doesn't resolve the issue for me

**Comment by mattermoran** [comment]
As mentioned previously changing kotlin version should do the trick.
More info can be found here https://github.com/flutter/flutter/issues/83834
