### ISSUE TITLE
Add Uber to map_laucher

### ISSUE THREAD

**Issue by camilledelouis** [mattermoran/map_launcher#108]
Hello everybody,

thank you for this packages, it's awesome !

I would like to have another choice : A link with Uber apps. I don't know if it's scheduled in your road map but it will be great if this option is integrated in your package.

What do you think about it ?

Thank again

**Comment by mattermoran** [comment]
Hi!
It should be possible to do. Will try to handle this when have some more time.
Linking documentation for my future self: https://developer.uber.com/docs/riders/ride-requests/tutorials/deep-links/introduction

If you feel like handling this, I'd review a pr :)

**Comment by camilledelouis** [comment]
Hi @mattermoran,

thanks for your quick response. It's amazing.

I've never write any package, so may be I need some times to handle this. And I have no time for the next months. But, in the future, I will need this feature. So if I handle this before you, I'll send you a pr.

**Comment by mattermoran** [comment]
The progress will be tracked here https://github.com/mattermoran/map_launcher/issues/111
