### ISSUE TITLE
On iOS, MapLauncher.installedMaps only returning apple maps 

### ISSUE THREAD

**Issue by cody-fjorge** [mattermoran/map_launcher#110]
This was working for a while, but recently only apple maps is being returned from .installedMaps. I have multiple supported map apps installed and have been able to use them in the past, but that is not the case anymore.

**Comment by mattermoran** [comment]
That's quite strange. So you saying it was fine before but all of a sudden it stops returning any maps other than apple maps? you sure url schemes were not removed from info.plist file?
if plist wasn't changed then what is the ios version? what device? can you try to run the example app from this repo and see if also no maps returned? do you actually have any other maps installed on a device (e.g you running on a simulator that only has apple maps)?
