### ISSUE TITLE
Waze problem on Android - It opens Waze but only shows empty startup widget

### ISSUE THREAD

**Issue by elmar001** [mattermoran/map_launcher#112]
It opens Waze but it comes with no route or destination pin - just like opening Waze yourself. Seems like there is a problem with passing parameters or something like that. So Waze ignores given destination lat& long and shows startup screen. I tried several recent versions of this map_launcher but all behave same.

**Comment by mattermoran** [comment]
I have just tried to run the example app and it seems to work ok.
Maybe it doesn't support the coords you are passing?

https://user-images.githubusercontent.com/29712386/163025093-8ae7cf62-927c-4aad-9b5a-5aa3291690c7.mp4

**Comment by elmar001** [comment]
Thanks man, you are right. Debugged it again and found the problem that stemmed from the input values. All good now, thanks for the quick response.

**Comment by mattermoran** [comment]
Glad it's sorted :)
