### ISSUE TITLE
Add waypoints to maps that support them

### ISSUE THREAD

**Issue by mattermoran** [mattermoran/map_launcher#113]
Find out which maps have support for waypoints and integrate
- [x] Google maps
- [ ] Apple maps

**Comment by SoftWyer** [comment]
It's possible to open directions with waypoints on Apple maps via a URL, rather than using MKLink, e.g. 

```
maps://https://maps.apple.com/maps?saddr=37.8078513,-122.404604&daddr=37.7705112,-122.4108267&daddr=37.759392,-122.5107336
```

[See this SO question](https://stackoverflow.com/questions/73193820/how-to-launch-apple-maps-with-multiple-stops-in-flutter)

**Comment by mattermoran** [comment]
@SoftWyer thanks! In fact it's possible using `MapKit` by just adding as many `MKMapItem` between origin and destination. I don't know why I never done that it's like couple minutes haha
I think I might release new version today with waypoints for apple maps

**Comment by mattermoran** [comment]
@SoftWyer could you try to install version from master branch and see if it all works fine for you? I have tested on my side and it seem to be ok. If there are no issues I will publish on pub
```yaml
map_launcher:
  git:
    url: https://github.com/mattermoran/map_launcher.git
```

**Comment by SoftWyer** [comment]
Will do, but it'll have to be tomorrow. I'll drop a comment here 😄

**Comment by SoftWyer** [comment]
> @SoftWyer could you try to install version from master branch and see if it all works fine for you? I have tested on my side and it seem to be ok. If there are no issues I will publish on pub
> 
> ```yaml
> map_launcher:
>   git:
>     url: https://github.com/mattermoran/map_launcher.git
> ```

That's working perfectly, no client side changes required which is great 👍 

Thanks for being so responsive, much appreciated.

**Comment by mattermoran** [comment]
Awesome. 
Version 2.5.0 is now available on pub :)

**Comment by artemsorochan** [comment]
@mattermoran is there a way on how to add title for waypoint also?

**Comment by mattermoran** [comment]
It doesn't look like google maps supports titles in directions mode. For iOS I guess it should be possible to that would require refactoring the waypoints as it currently just latlong. Maybe in the next major version but not anytime soon

**Comment by AristideVB** [comment]
Being able to add labels on way points would be incredible ! :)
