### ISSUE TITLE
In iOS, Origin title is not get displayed in apple map.

### ISSUE THREAD

**Issue by TharaniP** [mattermoran/map_launcher#116]
In iOS, I am passing originTitle to the showDirections method. but Origin title is not displayed on the apple map. 
Currently, its displaying as origin on the Bottom sheet and Map. But i want to display the origin title which is same like destination.

![Simulator Screen Shot - iPhone 13 Pro - 2022-05-02 at 19 03 19](https://user-images.githubusercontent.com/53432405/166242622-797aaaa1-d42e-405f-b71a-e769450f367a.png)
.

Thanks in advance.

**Comment by mattermoran** [comment]
@TharaniP well this is pretty epic. I seem to have made a typo 2 years ago and nobody complained before you xD
<img width="630" alt="image" src="https://user-images.githubusercontent.com/29712386/166243747-8c1218e2-62e7-4c5b-9ed1-57e650378b1d.png">

**Comment by mattermoran** [comment]
Released version 2.2.2 with fix for this :)

**Comment by TharaniP** [comment]
Thanks for the quick fix.
