### ISSUE TITLE
map_launcher error

### ISSUE THREAD

**Issue by cflima18** [mattermoran/map_launcher#12]
When I try to give the command flutter run, this problem happens.

- `map_launcher` does not specify a Swift version and none of the targets (` Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set
     the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

my configs.
cezar@MacBook-Pro-de-Cezar app-convenios-frota % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.1 19B88, locale pt-BR)
    • Flutter version 1.12.13+hotfix.8 at /Users/cezar/Desenvolvimento/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cezar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro • EF52A92B-6AAC-4EF6-A9B7-C9AF906A5F76 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

**Comment by mattermoran** [comment]
@cflima18 hi. my guess is that you created non swift version of flutter. If that's the case there are some workarounds to using swift plugins. You can find more here: https://github.com/flutter/flutter/issues/16049
Let me know if that solves your issue

**Comment by cflima18** [comment]
I ended up following the steps, but it's not working.

[!] Unable to determine Swift version for the following pods:

- `map_launcher` does not specify a Swift version and none of the targets (` Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

[!] Automatically assigning platform `iOS` with version` 9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile.


My Podfile

[Podfile.txt](https://github.com/mattermoran/map_launcher/files/4293739/Podfile.txt)

**Comment by mattermoran** [comment]
@cflima18  Have you tried creating a swift file in your project and a bridging header?

**Comment by mattermoran** [comment]
@cflima18 do you still have this issue? for adding bridging header you can try to follow those steps: https://github.com/mattermoran/map_launcher/issues/16#issuecomment-604252449

**Comment by mattermoran** [comment]
Closing this as there's no reply. Please reopen if issue still persists
