### ISSUE TITLE
iOS Apple Plans bug with address

### ISSUE THREAD

**Issue by SimonTellier** [mattermoran/map_launcher#120]
Hi,
maybe a new bug.
When i try to navigate with Apple Plans with address, MapLauncher didn't override Coords and title. My code works with Waze and Google maps.

```
await MapLauncher.showMarker(
        mapType: getMapType(mapTypeString: option.appNavigation),
        title: "${client.ent_raison}",
        coords: Coords(0, 0),
        extraParams: {'q': '${client.adresse1} ${client.ville} ${client.cp}'});
```

**Comment by mattermoran** [comment]
there's no proper support for launching using address yet. there's an issue for that https://github.com/mattermoran/map_launcher/issues/114
