### ISSUE TITLE
Not correct work with Yandex Maps

### ISSUE THREAD

**Issue by KonstantenKomkov** [mattermoran/map_launcher#123]
When user choose Yandex Map and map is opening field address to is empty and field address from contain value address to. With Yandex Navigator or another maps working good.

**Comment by mattermoran** [comment]
Do you mean yandex maps do not work without settings origin point? If yes that is expected behavour. the documentation states that both origin and destination points are required https://yandex.com/dev/yandex-apps-launch/maps/doc/concepts/yandexmaps-ios-app.html#yandexmaps-ios-app__buildroute
The only way I can think of to get it working is to request current location and then pass it as origin

Or is it something else?

**Comment by KonstantenKomkov** [comment]
You are right. If I add 'origin' coordinates routing work correct.
