### ISSUE TITLE
Android build started to fail

### ISSUE THREAD

**Issue by Zalexei** [mattermoran/map_launcher#126]
Worked before. Today with new build started to show this error in console:
`flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.2.3/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (14, 20): Redeclaration: MapType
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.2.3/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (16, 15): Redeclaration: MapModel
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.2.3/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (22, 7): Redeclaration: MapLauncherPlugin
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (14, 20): Redeclaration: MapType
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (16, 15): Redeclaration: MapModel
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (16, 37): Cannot access 'MapType': it is private in file
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (18, 43): Cannot access 'MapType': it is private in file
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (22, 7): Redeclaration: MapLauncherPlugin
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (36, 31): Cannot access 'channel': it is private in 'MapLauncherPlugin'
flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-2.3.0+1/android/src/main/kotlin/com/alexmiller/map_launcher/MapLauncherPlugin.kt: (37, 31): Cannot access 'context': it is private in 'MapLauncherPlugin'`

**Comment by mattermoran** [comment]
Seems like just the cache issue. Please try running `flutter clean` and then `flutter pub get` and build again

**Comment by mattermoran** [comment]
Probably same as https://github.com/mattermoran/map_launcher/issues/109

**Comment by Zalexei** [comment]
Thanks. Cleaning solved the issue.
