### ISSUE TITLE
Extended functionality for ios devices < 10.0

### ISSUE THREAD

**Issue by beto-hopee** [mattermoran/map_launcher#129]
i will extend it because it gives error in ios < 10.0 and our project want to support from ios 9.0

<img width="1135" alt="Screen Shot 2022-09-28 at 14 03 36" src="https://user-images.githubusercontent.com/110592909/192710905-37e2ad17-5ad9-4161-980e-dafbe9ed67aa.png">

**Comment by mattermoran** [comment]
Closing as flutter itself now doesn't support anything below ios 11.
