### ISSUE TITLE
use the user's default map app somehow (feature request)

### ISSUE THREAD

**Issue by Megamannen** [mattermoran/map_launcher#138]
You might want to to launch the users default map app.

(That feels like maybe an even more likely use case than a predefined list?)

**Comment by mattermoran** [comment]
The plugin was initially created to solve the specific need of showing a list of maps but I see your point. Might as well add something like MapType.default 
For now you can just check the current platform and provide appropriate map type

**Comment by Megamannen** [comment]
The default map configurable by the user on his phone, like default web browser and so on.

 I can choose if I want Google Maps or Here or Waze
 
 So just checking if (android) then GoogleMaps doesn't help if that is what you are suggesting?

**Comment by mattermoran** [comment]
Oh I see. I thought you meant default for a platform. The only way I know for this is to just call the geo:lat,long but for that you don't even need the plugin. The plugin is more for providing extended functionality the maps have to offer

**Comment by mattermoran** [comment]
Closing as it's outside the scope of this app
