### ISSUE TITLE
possible to launch using address?

### ISSUE THREAD

**Issue by jamesdixon** [mattermoran/map_launcher#14]
Hi,

First, great package. Thank you!

Second, is there an option to launch using address rather than coordinates?

Cheers.

**Comment by mattermoran** [comment]
Hi. Glad you like the plugin :)
There's currently no option to launch with an address and I'm not sure how many maps actually do support it. I'll take a look at that when I have time.

**Comment by santoshpro95** [comment]
Hi @mattermoran It can be possible in Swift code as you are passing only Lat and Lng, we can pass address in to it, 
private func getMapItem(latitude: String, longitude: String) -> MKMapItem {
    let coordinate = CLLocationCoordinate2DMake(Double(latitude)!, Double(longitude)!)
    let destinationPlacemark = MKPlacemark(coordinate: coordinate, addressDictionary: nil)

    return MKMapItem(placemark: destinationPlacemark);
}
Here you are passing nil in AddressDictionary, we can pass encode address and In url you need to pass like "url?q=<address>"

**Comment by magicleon94** [comment]
Hi @jamesdixon ,
as a temporary workaround I can suggest to use [this package](https://pub.dev/packages/geocoding) to obtain the coordinates from the address and then use with MapLauncher

**Comment by mattermoran** [comment]
It's now possible to do it for google maps with extraParams like so:
```dart
map.showMarker(
  coords: Coords(0, 0),
  title: title,
  zoom: zoom,
  extraParams: {
    'q': '200 Union St, San Francisco, CA 94133', // here just use an address it will override latlong
  },
);
```
the `q` params will override latlong. 

Later I will add proper support for address

**Comment by mtc-jed** [comment]
At least for Apple (as this is a problem for me, I had to entirely bypass map_launcher to use it, which kinda defeates the point of the package), I propose simply adding a condition `if(coords.latitude != 0)` to the line 69 `'saddr': '${coords.latitude},${coords.longitude}',` in `getMapMarkerUrl`.
The same general principle can probably be done for other maps if their APIs allow it. Should I make a pull request ?
I would also propose doing this behind a flag, at least for now.

**Comment by mattermoran** [comment]
@mtc-jed this plugin has never had an "official" way for using the address instead of coordinates so it's not quite fair to say that lack of this feature defeats the purpose of this plugin. 
Although I understand that this is a useful feature so I added it to a milestone for v3
Anything related to the address will be tracked in #114
