### ISSUE TITLE
Google Maps coordinates and title getting concatenated

### ISSUE THREAD

**Issue by James-A-White** [mattermoran/map_launcher#140]
Many thanks for the great package!

Using the package on IOS 16.1 / iPhone 8 when I pass in coordinates and a title to Google Maps, the two get concatenated with a '/' between them:

So if I pass coords Lat 52.8, Lon 4.4 with a title of 'Test" what I see on my Google Maps app is that it is unable to find the location because it is searching for this string:

52.8,4.4/Test

I'm guessing somehow this is user error because no one else has reported it, but I can't figure out what's going on. 

For now, I'm passing an empty string for the title for Google Maps and it works fine.

It works well with Apple Maps and Waze.

I've updated to the latest version of Google Maps.

Thanks!

**Comment by mattermoran** [comment]
Hey. This is very strange. I just tried on the latest version of google maps and it seems to be working just fine (see video attached)

Can you try to run the example app and see if you get the same issue. If yes then provide version of google maps you are using. I wonder if something has changed there but I doubt. 

https://user-images.githubusercontent.com/29712386/213390836-92e1924d-5ccc-4c96-8a05-7ccabe1e4c9c.MP4

**Comment by mattermoran** [comment]
@James-A-White is this still an issue?

**Comment by mattermoran** [comment]
I'm going to close this as it seem to be working as expected. Let me know if not
