### ISSUE TITLE
Google is asking to sign in when clicking on Directions

### ISSUE THREAD

**Issue by rvharjinderbains** [mattermoran/map_launcher#141]
Google map opened succussfully but it ask to sign in. However I Google map is already SIgned in. Please let me know if there is any solution. 
![flutter_01](https://user-images.githubusercontent.com/105272009/217240263-3b4482f7-6414-4f76-a773-f9e8e356498f.png)

**Comment by mattermoran** [comment]
I think that happens because you have not specified the origin (starting point) and you also have location services disabled so google maps just doesn't know how to show directions. 
As to why is it asking to login when you already logged in there's nothing this plugin can do about it

**Comment by rvharjinderbains** [comment]
Ok thank you. I will check it

**Comment by rvharjinderbains** [comment]
@mattermoran thank you for your response. Now it is working fine
