### ISSUE TITLE
Google Play rejects the app

### ISSUE THREAD

**Issue by mobikats** [mattermoran/map_launcher#143]
"We are unable to approve your app’s use of QUERY_ALL_PACKAGES permission because the declared task can be done with a less broad app-visibility method."

I believe it is this package that currently requires the QUERY_ALL_PACKAGES permission - could that be refined?

**Comment by mattermoran** [comment]
Hmm that's the first rejection I hear for that permissions. 
There seems to be a way to not use package manager's `getInstalledPackages` method and instead do more like on ios by trying to see if app with package name supports opening url scheme.
Should probably work but won't know until I try maybe this or next week

**Comment by mobikats** [comment]
Thanks @mattermoran for the quick response and thoughts on that, I was considering removing it for now (and losing the functionality) but if you did have a solution that would be fantastic. 

I can't be the only one facing it either, it looks like Google are becoming a lot stricter all of a sudden (even though some would say that it’s a bit late in the day - the barn was not only left open, it had a farm shop for posh people built in it).

**Comment by tjeffree** [comment]
@mobikats If you are still using this package and are in a place to try a submission feel free to test out my fork that is in this merge request:

https://github.com/mattermoran/map_launcher/pull/152

The app I'm working on isn't quite ready for review yet, but in testing this appears to function the same as the original detection method but without using `getInstalledApplications`.

**Comment by mobikats** [comment]
Thanks @tjeffree but I must have solved this at the time by removing the package I expect. 
Thanks for fixing!
