### ISSUE TITLE
ShowDirections method not working on ios 16.4.1 and Google Maps

### ISSUE THREAD

**Issue by SherpaMiguel** [mattermoran/map_launcher#146]
ShowDirections is working well on Apple Maps but not on Google Maps. It opens the browser although Google Maps app is installed.

**Comment by EDnny12** [comment]
add this in Info.plist file:

<key>LSApplicationQueriesSchemes</key>
<array>
    <string>comgooglemaps</string>
    <string>baidumap</string>
    <string>iosamap</string>
    <string>waze</string>
    <string>yandexmaps</string>
    <string>yandexnavi</string>
    <string>citymapper</string>
    <string>mapswithme</string>
    <string>osmandmaps</string>
    <string>dgis</string>
    <string>qqmap</string>
    <string>here-location</string>
    <string>tomtomgo</string>
</array>

**Comment by gelas7** [comment]
My fault. Restarting iphone did the trick. Sorry.
