### ISSUE TITLE
The Plugin doesn't work on iOS

### ISSUE THREAD

**Issue by Goran-coder** [mattermoran/map_launcher#149]
I have a Mac and I tried running the flutter app that uses map_launcher plugin on Iphone 14 emulator. The same app with your plugin works on android emulator. When I debug for Iphone emulator from vscode I get the following error:
![tata-gotovo](https://github.com/mattermoran/map_launcher/assets/116684618/e2d14d47-e5c0-49d0-904d-2532a2020ba4)

Also when I try in xcode I get this error:
![tata2](https://github.com/mattermoran/map_launcher/assets/116684618/709ffac7-85a2-4acb-a2c4-5cba10ea8f37)

I have added needed lines to Info.plist
![tata3](https://github.com/mattermoran/map_launcher/assets/116684618/9d790cbd-8e83-42a1-a96b-19dcfab88660)
I am not sure what is wrong. I have tried changing the Podfile to add that dependency from cocoapods, but cocoapods does not know what is map_laucher. So `pod search map_launcher` gives back 
`[!] Unable to find a pod with name, author, summary, or description matching 'map_launcher'`. 
Can someone help?

**Comment by mattermoran** [comment]
I'm going to need more info to debug. Can you provide `flutter doctor --verbose` output?
Also could you try to create a brand new flutter app and add map launcher as a dependency to see if it still happens?

**Comment by Goran-coder** [comment]
So I have removed the dependency and the code for opening maps. Then the emulator will start. While the emulator being 'hot', I add the dependency and the code. Then I do the hot restart and the following error happens when I click the button that opens maps:
![tata6](https://github.com/mattermoran/map_launcher/assets/116684618/f8f796c7-e90c-4b83-a248-39ffe8e8f961)
When I close the connection so the emulator is no longer 'hot' it will not start again and everything the same happens as the original post. All errors are the same.

**Comment by mattermoran** [comment]
Could you also share your `pubspec.yaml` as well as the `Podfile`?

**Comment by Goran-coder** [comment]
Here is the `pubspec.yaml`:
![tata9](https://github.com/mattermoran/map_launcher/assets/116684618/7792c1d6-db99-4148-b963-89b011c9013f)
![tata8](https://github.com/mattermoran/map_launcher/assets/116684618/fea8916a-8c53-4d91-b1e6-319da5baed56)

And here is the `Podfile`:

![tata7](https://github.com/mattermoran/map_launcher/assets/116684618/03b97856-4e43-493d-951d-fdb1b789c81a)

**Comment by mattermoran** [comment]
As you mentioned it works in a brand new project which means most likely there was some caching issue. 
I'm closing this. Let me know if you still think it's a problem with this plugin.
