### ISSUE TITLE
google maps issue (iOS)

### ISSUE THREAD

**Issue by jamesdixon** [mattermoran/map_launcher#15]
Hi again,

I'm noticing some interesting things with regards to opening Google Maps on iOS.

In the example, `title` indicates the title of the pin. However, this call `comgooglemaps://?q=$title&center=${coords.latitude},${coords.longitude}` will actually search for whatever `title` is near the coordinates passed in. It is not really a title, it's a search query. For example, if I pass in "My House" as `title` and provide coordinates for my house, I get a "no results" message in Google Maps because it's actually searching for the term "My House" that is near the coordinates passed in.

All that said, it seems like a better option is to leave off `center` completely from the url. This will allow you to search for an address (see #14) or coordinates. 

However, if you want to add a title to the pin, here's what I'm seeing:

It can be done when you're passing coordinates by using the following url: `comgooglemaps://?q=$title($description)` and it will automatically leave off the description in the query and only show it in the bottom card.

However, if you pass an address as the `title` for some reason, it does not remove the description so you end up with something like `111 Lala Lane (My Description)` which will bring up a message to correct the query.

I know I just wrote a lot here, so let me know if it's clear!

**Comment by mattermoran** [comment]
I see what you're saying. Google Maps generally has issues with showing title on a pin (it just stopped working on Android since last year). I'll see if there's another way to show the title on ios and if not well then google maps just won't have it.

**Comment by mattermoran** [comment]
Fixed in https://github.com/mattermoran/map_launcher/pull/18
