### ISSUE TITLE
add namespace

### ISSUE THREAD

**Issue by m-derakhshi** [mattermoran/map_launcher#156]
A problem occurred configuring project ':map_launcher'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

**Comment by mattermoran** [comment]
fixed in https://github.com/mattermoran/map_launcher/pull/157
