### ISSUE TITLE
Not all available  apps returned on some Android devices

### ISSUE THREAD

**Issue by frankvollebregt** [mattermoran/map_launcher#159]
On some devices, some apps do not show up in the installed apps list. Anecdotally, it seems like there sometimes is 1 missing.

# My observations
### On a Google Pixel 7
_running Android 13_
In the current version of `map_launcher`, TomTom Go does not show up, even though it is installed.

In a version including the changes made in #158, TTGO shows up, but Sygic is not shown.

### On a Samsung Galaxy S9+
_running Android 10_
In the current version of `map_launcher`, TomTom Go does show up as you would expect.

I'll investigate more and add more devices/configurations if I can, but it seems something is amiss either with the package manager returning the installed applications, or with this package parsing and filtering them properly.

**Comment by mattermoran** [comment]
Pretty simple actually. Looks like it was missing in the AndroidManifest file so it was not visible. And that pr you mention did add it for both regular and fleet. 

<img width="1385" alt="image" src="https://github.com/mattermoran/map_launcher/assets/29712386/11b5c692-3fb7-415b-b213-8abb65561096">

**Comment by frankvollebregt** [comment]
Ah, that would explain it. Awesome, thank you.

Would be awesome to merge some of these new navigation apps into a release soon! :D

**Comment by mattermoran** [comment]
Yeah I got too ambitious with complete rewrite of the package but never have enough time to work on it so I consider just putting that idea away for now and just sort out existing prs. Hopefully this week!
