### ISSUE TITLE
Unable to determine Swift version

### ISSUE THREAD

**Issue by SeanOThomas** [mattermoran/map_launcher#16]
When attempting to update run `pod update`, I get the following:

```
[!] Unable to determine Swift version for the following pods:

- `map_launcher` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

Can you add SWIFT_VERSION? Thanks!

**Comment by mattermoran** [comment]
Hi. I think you are trying to add this plugin (swift) to your objective c based project. If that's the case you try those steps:
1. Open your project in Xcode
2. Click File -> New -> File. Select Swift File. You can call it anything. It will ask you want to create bridging header as well click yes.
3. Run `flutter clean`
4. try to update again

Let me know if this doesn't work and we'll try to find another solution

**Comment by SeanOThomas** [comment]
Hmm, I already configured Swift for the project. You should search the
issue I'm having -- there's been many other packages that have had to
address this.

**Comment by mattermoran** [comment]
Ok I see. I added swift version in Podspec file. Can you try to add the plugin from github and see if that fixes the issue? You can add this in your pubspec.yaml:
```
map_launcher:
  git:
    url: https://github.com/mattermoran/map_launcher
    ref: master
```

**Comment by SeanOThomas** [comment]
That worked. Cheers man!

**Comment by mattermoran** [comment]
Fantastic. Made a proper release. Version 0.4.4 should work for you now.

**Comment by SeanOThomas** [comment]
Hey man, I spoke too soon. I'm now seeing the following build error: 

```
Xcode's output:
↳
    /Users/sthomas/flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-0.4.4/ios/Classes/MapLauncherPlugin.m:2:9: fatal error: 'map_launcher/map_launcher-Swift.h' file not found
    #import <map_launcher/map_launcher-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

I've tried `flutter pub get` and doing a `pod install`. Any ideas?

**Comment by mattermoran** [comment]
Hmm you might be missing `use_frameworks!` in your Podfile. Try to add it and see if it makes a difference
![image](https://user-images.githubusercontent.com/29712386/77895902-07daad80-72aa-11ea-8bd1-d19309b5fbba.png)

**Comment by mattermoran** [comment]
Closing this as there's no reply. Please reopen if issue still persists
