### ISSUE TITLE
Bug: Using it with 'Waze'

### ISSUE THREAD

**Issue by burekas7** [mattermoran/map_launcher#162]
Hi, @mattermoran 

Is it a known issue that open the 'Waze' app with this package doesn't work?

It only opens the 'Waze' app without the location or option for route calculation etc...

**Comment by mattermoran** [comment]
hmm strange no I don't think so. 
just tried on android and it seems to be working
![IMAGE 2023-09-14 3:41:47 PM](https://github.com/mattermoran/map_launcher/assets/29712386/65505a77-7fa9-4b8b-9b76-a08e658be03a)

**Comment by burekas7** [comment]
@mattermoran 

Can you show me a code example?
Strange, maybe I'm using it wrong. But with GoogleMaps it's ok.

Which Android version do you have?

**Comment by burekas7** [comment]
Edit:
I think it's a bug with Waze.
It seems that as I zoom out from my location, the map does not update in detail.
So when it opens a location which is not in my country it looks like a blank map.

**Comment by burekas7** [comment]
By the way, is there an option for 'navigate to' from my current location or it only opens the navigation app in the requested location?

**Comment by mattermoran** [comment]
Yup I guess it's just a wave thing :)

**Comment by Juggler98** [comment]
I'm also facing this issue on Android 11

**Comment by mattermoran** [comment]
@Juggler98 I don't think I can do anything about as it's a waze issue but let me know if you think something on the package side can be done

**Comment by Juggler98** [comment]
Thanks for the quick response. I guess something must changed in the package, because in version 2.3.0 it works fine.

**Comment by mattermoran** [comment]
Just checked the diff and there's no changes that could have caused it. Most likely waze app updated. You can try to install 2.3.0 and see but I'm pretty sure it's same.
