### ISSUE TITLE
`showMarker` and `showDirections` Futures don't complete on success on iOS

### ISSUE THREAD

**Issue by vincent-hoodoo** [mattermoran/map_launcher#163]
Hello and thank you for the great and useful plugin.

I noticed that the Futures returned by `MapLauncher.showMarker` and `MapLauncher.showDirections` never complete on success on iOS (they do on Android).

It's probably just a matter of adding a call to `result` on https://github.com/mattermoran/map_launcher/blob/master/ios/Classes/SwiftMapLauncherPlugin.swift#L194 and on https://github.com/mattermoran/map_launcher/blob/master/ios/Classes/SwiftMapLauncherPlugin.swift#L230.

It's problematic in our case, since we wait for these Futures to complete to perform other logic.

**Comment by mattermoran** [comment]
Hey @vincent-hoodoo 
You're right, it should've definitely called the `result`. 

Will fix up today :)

**Comment by mattermoran** [comment]
It's now fixed in v3 :)
