### ISSUE TITLE
Google maps aren't seen on IOS.

### ISSUE THREAD

**Issue by mb1shka** [mattermoran/map_launcher#169]
Hello! 
On my Iphone installedMaps doesn't return google maps as an available variant.
I've been looking through some issues but haven't found anythig similar. 

IPhone info (who knows, may be it will help):
7 Iphone
14.7.1 IOS version
Google maps and Apple maps are installed, but only apple maps are being shown (checked other maps before on Android, works fine).

Debug shows:

<img width="811" alt="Screenshot 2023-11-27 at 03 00 29" src="https://github.com/mattermoran/map_launcher/assets/80235393/8b35a3f3-87c2-4d6d-b3f2-362917f3cbf4">

Only IOS has this issue in our case... Android works fine.

**Comment by mb1shka** [comment]
<img width="363" alt="Screenshot 2023-11-27 at 03 06 56" src="https://github.com/mattermoran/map_launcher/assets/80235393/1a2a7747-5a91-44aa-b36a-012c858064e7">
My info plist also contains google maps.
Googling something about Info.plist didn't help either.

**Comment by mattermoran** [comment]
Hmm just tested on my side and see no issues. 
Could you clone the repo and run the example project to see if it shows up for you?
If it does then it's something your setup and if not then something with the map which I would find very weird
<img src="https://github.com/mattermoran/map_launcher/assets/29712386/6b324a4d-72ee-41c0-942f-fa61d69748f4" width="300">

**Comment by mb1shka** [comment]
@mattermoran 
![image](https://github.com/mattermoran/map_launcher/assets/80235393/f3ab2c72-8d95-40f2-adf1-6388769a4c46)

It took several hours to understand *crying emoji*

Sorry for bothering ~ I'll close the issue.
