### ISSUE TITLE
No support for Android Profile

### ISSUE THREAD

**Issue by mLegeay** [mattermoran/map_launcher#170]
Hi,

I've got trouble with Android. In my workplace, our phones are separated between work profile and personal profile
https://www.android.com/intl/en_gb/enterprise/work-profile/

My maps apps are on personal profile side, but my app calling for apps is on the work profile side
If I use launch_url to use Google Maps, it works fine, it will open google maps on personal profile side.

Would it be possible to get all available maps on which either side they are on?

**Comment by mattermoran** [comment]
I did some research and I don't think it's possible to get list of maps across different profiles and that's a security risk. There may be ways to actually do that in android but that would not pass the google review. 

I'll close this issue unless you think there's a proper solution.
