### ISSUE TITLE
 showDirections only Preview mode for Google Maps

### ISSUE THREAD

**Issue by tiagomn** [mattermoran/map_launcher#174]
Hi Guys

I have been facing an issue when launching Google Maps on Android, it only shows Preview mode. There is no "Start" button to start the navigation.

Is it an issue? Because I have an app in Ionic which "Start" works pretty well.

![example1](https://github.com/mattermoran/map_launcher/assets/4093380/a35cf4f5-7d9a-4405-92bd-c2a8d9d84c4a)

**Comment by mattermoran** [comment]
It's not a bug. You are passing both starting location and destination that's why you are getting preview option. 
if you do not pass the origin then it will use your current location in which case you get the actual navigation from your current location

**Comment by tiagomn** [comment]
Perfect, that's make sense!
