### ISSUE TITLE
Launch query support

### ISSUE THREAD

**Issue by mjablecnik** [mattermoran/map_launcher#178]
Hello, do you support also launch query similar as [maps_launcher](https://pub.dev/packages/maps_launcher) where I fill address and maps are launched there?

**Comment by mattermoran** [comment]
heya. not at the moment, no. 
there's an open issue for it I just haven't had time for it yet https://github.com/mattermoran/map_launcher/issues/114

**Comment by mjablecnik** [comment]
Ok, it would be great if you could add this functionality. 
I think it could be very useful for many developers, and I wouldn't need to use maps_launcher alongside map_launcher.. :)

**Comment by mattermoran** [comment]
Yeah I see what you are saying hah. These 2 packages serve slightly different purposes but having to use both might be confusing. 
I'll see what I can do without bloating the api. 

I'll close this issue as a duplicate you can sub for status updates on the linked issue.
