### ISSUE TITLE
Marker not showing in Apple Maps

### ISSUE THREAD

**Issue by sarathn91** [mattermoran/map_launcher#181]
Using below code to open the default maps app:

`await MapsLauncher.launchCoordinates(latitude, longitude, description ?? "");`

Upon opening, the location marker is not showing in Apple Maps app. I'm passing the correct latitude and longitude and it moves to the correct location, just the red marker that we normally see is not displaying.

It's working with Google maps.

**Comment by mattermoran** [comment]
heh wrong package :)
