### ISSUE TITLE
MapLauncher.installedMaps returns only one item

### ISSUE THREAD

**Issue by shinsenter** [mattermoran/map_launcher#19]
MapLauncher.installedMaps returns only one item.

My iPhone (iOS 13.4) have both Apple Maps and Google Maps.

**Comment by shinsenter** [comment]
MapLauncher.installedMaps returns only one item.

My iPhone (iOS 13.4) have both Apple Maps and Google Maps.

**Comment by mattermoran** [comment]
Hi. Did you add "comgooglemaps" in your info plist file?
![image](https://user-images.githubusercontent.com/29712386/80199054-7b769d00-8653-11ea-8971-fff06e679d89.png)

**Comment by shinsenter** [comment]
@mattermoran 
I did add above setting into Info.plist, following your instructions at pub.dev

**Comment by mattermoran** [comment]
hmm it's strange then. Can you try to run `flutter clean` command and then rebuild your project?

**Comment by mattermoran** [comment]
Just thought it might be caching related but if `flutter clean` doesn't help you can try to install other maps this plugin supports and see if any show up

**Comment by shinsenter** [comment]
flutter clean, removing pub cache, solved the problem.
