### ISSUE TITLE
Waypoints not working in Apple Maps

### ISSUE THREAD

**Issue by bjamturley** [mattermoran/map_launcher#191]
Hello, thanks for putting this package together. I have a basic example here which attempts to open a route with series of waypoints in Google and Apple Maps. This works fine in Google, but not in Apple where only the first waypoint appears as the destination. See the screenshots and minimal working example below. Any suggestions?

```
MapLauncher.Coords origin = MapLauncher.Coords(position.latitude, position.longitude);
MapLauncher.Coords destination = MapLauncher.Coords(_destination!.latitude, _destination!.longitude);
List<MapLauncher.Waypoint> waypoints = 
    waypointsList.map((point) => MapLauncher.Waypoint(point[0], point[1])).toList();

MapLauncher.DirectionsMode directionsMode;
switch (routeMode) {
  case RouteMode.walk:
    directionsMode = MapLauncher.DirectionsMode.walking;
    break;
  case RouteMode.bike:
    directionsMode = MapLauncher.DirectionsMode.bicycling;
    break;
  case RouteMode.drive:
    directionsMode = MapLauncher.DirectionsMode.driving;
    break;
}

MapLauncher.MapType mapType;
switch (service) {
  case 'google':
    mapType = MapLauncher.MapType.google;
    break;
  case 'apple':
    mapType = MapLauncher.MapType.apple;
    break;
  default:
    mapType = MapLauncher.MapType.google;
}

await MapLauncher.MapLauncher.showDirections(
  mapType: mapType,
  origin: origin,
  destination: destination,
  waypoints: waypoints,
  directionsMode: directionsMode,
);
```

<img src="https://github.com/user-attachments/assets/e6874a97-5817-4f57-b45f-7ca0c3327b06" alt="drawing" width="200"/>
<img src="https://github.com/user-attachments/assets/6c5c574b-a05d-4f18-8105-c877a35e1da7" alt="drawing" width="200"/>

**Comment by mattermoran** [comment]
seems like apple maps does not support waypoints for walking. you can toggle the drive mode and will see waypoints for as expected. nothing really I can do here :(

**Comment by bjamturley** [comment]
Got it, thanks for the help. Hope they add the functionality in the future.
