### ISSUE TITLE
Google maps Icon has been updated

### ISSUE THREAD

**Issue by javipelopi** [mattermoran/map_launcher#20]
Hi!

Google maps has updated their Icon, consider changing the asset. I attach the new icon in a PNG, however I don't know if you have some icons guidelines to follow.

Thanks in advance!

![Maps_Pin_FullColor max-1000x1000](https://user-images.githubusercontent.com/3465170/80402047-9b10fe00-88bd-11ea-9cdb-ca8ec0e12d79.png)

**Comment by mattermoran** [comment]
Hey @javipelopi 
Thanks for reminding.
I'll update soon

**Comment by mattermoran** [comment]
I'll close this as it will be updated in the v1 release and be part of https://github.com/mattermoran/map_launcher/issues/17
