### ISSUE TITLE
Here Maps

### ISSUE THREAD

**Issue by wesleifelix** [mattermoran/map_launcher#23]
How to add Here Maps to list of avaliable services?

**Comment by mattermoran** [comment]
Hi @wesleifelix 
Do you mean how could add it yourself? In that case you can take look at how other people contributed, e.g this pull request: https://github.com/mattermoran/map_launcher/pull/22
Let me know if that helps

**Comment by aleksandr-m** [comment]
See #77

**Comment by mattermoran** [comment]
Was added in #77
