### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite))

### ISSUE THREAD

**Issue by Donwaztok** [mattermoran/map_launcher#24]
After imported  map_launcher: ^0.5.0 on pubspec.yaml got this error on creating db, on method getDatabasesPath()

`return openDatabase(join(await getDatabasesPath(), DB_PATH), ... )`

my pubspec
`name: a
description: a

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  map_launcher: ^0.5.0
  device_info:  ^0.4.2+4
  flutter_launcher_icons: ^0.7.4
  font_awesome_flutter: ^8.7.0
  android_alarm_manager: ^0.4.5+4
  path_provider: ^1.6.1
  open_file: ^3.0.1
  camera: ^0.5.7+4
  sqflite: ^1.3.0+1
  background_location: ^0.0.9+3
  painter: ^0.3.2
  wakelock: ^0.1.3+4
  url_launcher: ^5.4.2
  google_map_polyline: ^0.2.0+1
  location: ^2.5.1
  flutter_polyline_points: ^0.1.0
  google_maps_flutter: ^0.5.24+1
  http: ^0.12.0+4
  dio: ^3.0.9
  bloc_pattern: ^2.5.1
  intl: ^0.16.1
  f_logs: ^1.3.0-alpha-02
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"`

flutter doctor -v

`[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [versÃ£o
    10.0.19041.329], locale pt-BR)
    • Flutter version 1.17.3 at C:\Users\igord\flutter
    • Framework revision b041144f83 (12 days ago), 2020-06-04 09:26:11 -0700  
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at C:\Users\igord\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java    
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\igord\AppData\Local\Programs\Microsoft VS Code      
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android R (API 29)       
      (emulator)

• No issues found!`

**Comment by mattermoran** [comment]
Hmm I don't really see the connection here. map_launcher does not have any dependencies especially sqflite. Could you start by running “flutter clean” command then restarting your emulator and see if issue is still there. If that doesn't help then we'll see what else could be causing it

**Comment by Donwaztok** [comment]
I dont see a connection too. I was thinking that should be some conflict , that's why I send the pubspec

I tried flutter clean, re cloned the repository, re creating my emulator and nothing :/

**Comment by mattermoran** [comment]
Interesting. Let's try to find out what's causing it. Could you create a new project and start adding your plugins one by one to see which one map_launcher conflicts with? I would do it myself but I won't have access to my computer in the next couple days

**Comment by Donwaztok** [comment]
Omg, i don't know what is happening.
Created a new project and copied the method that was giving error (getDatabasesPath()) and imported every package one by one. No errors

Copied the entire pubspec, no error.
Back to original project and just added map_launcher in pubscpec, without using. Erro =/

**Comment by Donwaztok** [comment]
Ty for the help. i'll close this issue and watch only on sqflite https://github.com/tekartik/sqflite/issues/452

**Comment by sharmaAshish-dev** [comment]
I too had the same problem  #MissingPluginException and fixed it by running flutter clean and uninstalling existing app and reinstalling the app.
