### ISSUE TITLE
map_launcher and google_maps_flutter use same enum

### ISSUE THREAD

**Issue by pazhut** [mattermoran/map_launcher#26]
i have an app that includes google map as widget, i would like to give the user the option to open a navigation app once they selected a pin from the map, so i have both map_launcher and google_maps_flutter being used in the same page.

i am getting the following error:
Compiler message:
lib/screens/two_widget/two_widget.dart:279:30: Error: 'MapType' is imported from both 'package:google_maps_flutter_platform_interface/src/types/ui.dart' and 'package:map_launcher/map_launcher.dart'.
                    mapType: MapType.normal,

is there a way to change the MapType enum in map_launcher to something like: MapLauncherType ?

Thanks much

**Comment by mattermoran** [comment]
hey @pazhut 
absolutely. you can just import map_launcher into a variable rather than globally like
`import 'package:map_launcher/map_launcher.dart' as ml;`
in this case all the map launcher methods will be available under `ml` variable
e.g `ml.MapType` or `ml.MapLauncher.launchMap(...)`

**Comment by pazhut** [comment]
Thanks much for the help
