### ISSUE TITLE
Swift static library in Objective-C

### ISSUE THREAD

**Issue by fisherjoe** [mattermoran/map_launcher#28]
Some advice ^^
In some project, it would be error when #import <map_launcher/map_launcher-Swift.h> in file "MapLauncherPlugin.m".
User as follow would be more compatibility：

#if __has_include(<map_launcher/map_launcher-Swift.h>)
#import <map_launcher/map_launcher-Swift.h>
#else
// Support project import fallback if the generated compatibility header
// is not copied when this plugin is created as a library.
// https://forums.swift.org/t/swift-static-libraries-dont-copy-generated-objective-c-header/19816
#import "map_launcher-Swift.h"
#endif

**Comment by mattermoran** [comment]
Hey. Thanks I'll take a look at that!

**Comment by agilidadesoftware** [comment]
Hello. I´m compiling my app using codemagic.io
I have this error, and I think that I depend on this fix...

    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/map_launcher-0.12.0/ios/Classes/MapLauncherPlugin.m:2:9: fatal error: 'map_launcher/map_launcher-Swift.h' file not found
    #import <map_launcher/map_launcher-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mattermoran** [comment]
Sorry it took me forever to get to this. Added in version 0.12.2

**Comment by agilidadesoftware** [comment]
Thanks a lot. Congratulations for this library.
