### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by botty87** [mattermoran/map_launcher#30]
I user workmanager plugin and everything is fine when execute some code in background, even calling other plugins, such Hive.
When I add map_launcher plugin in pubspec and I run again the same code I have a MissingPluginException every time that I try to call any other plugins inside the workmanager backround job.

Even only run the app without any use of workmanager and similar I get "Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@ed058f3) but could not find and invoke the GeneratedPluginRegistrant" on the debug console when I launch the app.

Can you help me, or solve this trouble? Your plugin is really amazing and I like to use it!

**Comment by mattermoran** [comment]
Hey @botty87 
Could you provide more info like `flutter doctor` output and what device you are running on?

**Comment by botty87** [comment]
- flutter doctor:


[✓] Flutter (Channel stable, v1.17.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.17.2 at /home/botty/Android/flutter
    • Framework revision 5f21edf8b6 (6 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version
29.0.3)
    • Android SDK at /home/botty/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/botty/.android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/botty/.android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android
10 (API 29) (emulator)


   - I run on the emulator


To reproduce the problem you can create a new project like the default one
in Android Studio. Dependencies in pubspec:

map_launcher: ^0.6.0
workmanager: ^0.2.3
hive: ^1.4.1+1
hive_flutter: ^0.3.0+2


main.dart:

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) {
    Hive.initFlutter();
    print("Native called background task"); //simpleTask will be emitted here.
    return Future.value(true);
  });
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
  Workmanager.registerOneOffTask("uniqueName", "taskName");
  runApp(MyApp());
}

In the same code above if you comment map_launcher everything is fine.

**Comment by mattermoran** [comment]
alright I see the issue now. Looks like I may need to update the plugin to support v2 of embedding. I will try to do it tomorrow

**Comment by mattermoran** [comment]
hey @botty87 
could you try to install new version of map_launcher with v2 embedding and see if it works for you? I've tested and it seems to be fine on my side. If all good I'll make a release.
to install from github branch you can add this as a dependency:
```
  map_launcher:
    git:
      url: https://github.com/mattermoran/map_launcher
      ref: android-embedding-v2
```

and then run `flutter clean`

**Comment by botty87** [comment]
Perfect! Great work, thank you!

**Comment by mattermoran** [comment]
Awesome. Version 0.8.0 with this change is available on pub now
