### ISSUE TITLE
 android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context 

### ISSUE THREAD

**Issue by LeonidVeremchuk** [mattermoran/map_launcher#31]
Hello. Thank you for this plugin.
Have problem with Android.

 android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/MethodChannel#map_launcher( 6917): 	at android.app.ContextImpl.startActivity(ContextImpl.java:994)
E/MethodChannel#map_launcher( 6917): 	at android.app.ContextImpl.startActivity(ContextImpl.java:970)
E/MethodChannel#map_launcher( 6917): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
E/MethodChannel#map_launcher( 6917): 	at com.alexmiller.map_launcher.MapLauncherPlugin.launchGoogleMaps(MapLauncherPlugin.kt:73)

Looks like problem with android side.I will try fix in fork

**Comment by mattermoran** [comment]
@LeonidVeremchuk hey yeah looks like I screwed something up while migrating to embedding v2. If you know how to fix it that would be nice. If not you can just use version 0.7.1 for now

**Comment by LeonidVeremchuk** [comment]
FLAG_ACTIVITY_NEW_TASK requirement is now enforced

With Android 9, you cannot start an activity from a non-activity context unless you pass the intent flag FLAG_ACTIVITY_NEW_TASK. If you attempt to start an activity without passing this flag, the activity does not start, and the system prints a message to the log.

Note: The flag requirement has always been the intended behavior, and was enforced on versions lower than Android 7.0 (API level 24). A bug in Android 7.0 prevented the flag requirement from being enforced.

Solution: 
![image](https://user-images.githubusercontent.com/5869861/87425495-0a091380-c5de-11ea-86cd-060b014118a8.png)

**Comment by LeonidVeremchuk** [comment]
Please add to **launchGoogleMaps** and **launchMap** function ))

**Comment by mattermoran** [comment]
ha interesting. so it's not really related to embedding change then. I'm surprised it didn't pop up before. 
I'm going to add this change then. Thanks for the info!

**Comment by LeonidVeremchuk** [comment]
Ok. Thanks!

**Comment by mattermoran** [comment]
@LeonidVeremchuk version 0.8.1 with this fix is now on pub
