### ISSUE TITLE
Open For Navigation

### ISSUE THREAD

**Issue by M6268** [mattermoran/map_launcher#33]
Is there any way to show the direction  as an option.

**Comment by allanwolski** [comment]
I need this too.

**Comment by guilhermedaldim** [comment]
Me too.

**Comment by krayony** [comment]
same

**Comment by mattermoran** [comment]
oh didn't think there's such a demand for this feature. Technically right now basically all the map markers have navigate button like this: 
![image](https://user-images.githubusercontent.com/29712386/88447302-64b73080-ce64-11ea-9680-37e8c64a479c.png)
![image](https://user-images.githubusercontent.com/29712386/88447303-654fc700-ce64-11ea-89e7-c351a40f1125.png)

but I assume you want screen similar to this open from the app, right?
![image](https://user-images.githubusercontent.com/29712386/88447326-93cda200-ce64-11ea-88e2-cca1a79a6a11.png)

**Comment by mattermoran** [comment]
Started working on it. You can track progress here: https://github.com/mattermoran/map_launcher/pull/34

**Comment by allanwolski** [comment]
Great job, @mattermoran 
Thank you very much for this feature.

**Comment by mattermoran** [comment]
@M6268 @allanwolski @guilhermedaldim @krayony 
Version 0.9.0 with directions is not available on pub!
