### ISSUE TITLE
Is there any way to add way points(Add stops) between source and destinations?

### ISSUE THREAD

**Issue by DhavalRKansara** [mattermoran/map_launcher#35]
Reference link :

**Directions examples using waypoints:**  https://developers.google.com/maps/documentation/urls/get-started#more-examples

**Example:** https://www.google.com/maps/dir/?api=1&origin=Paris,France&destination=Cherbourg,France&travelmode=driving&waypoints=Versailles,France%7CChartres,France%7CLe+Mans,France%7CCaen,France

**Comment by mattermoran** [comment]
Version 0.11.0 now supports waypoints for Google maps. Later will check if other maps support that

**Comment by DhavalRKansara** [comment]
Thanks, @mattermoran. Please add comments on the same issue when you provide support for the same in apple maps too.

**Comment by dmanzanomartin** [comment]
Hi, when I add the map with waypoints on IOS it tell me to set the destination and doesn’t show the route right, on Android it shows automatically, do you know how can I fix it?

**Comment by DhavalRKansara** [comment]
@mattermoran Is there any update for the waypoints support in other maps(Mainly Apple Map)?

**Comment by mattermoran** [comment]
The progress for waypoints will be tracked in #113
