### ISSUE TITLE
Rely on the system to find maps?

### ISSUE THREAD

**Issue by AAverin** [mattermoran/map_launcher#36]
Is there a way to rely on system to find maps?
On Android this should equivalent to firing `geo` intent with coordinates.
On iOS there also seem to be some option: https://stackoverflow.com/questions/28604429/how-to-open-maps-app-programmatically-with-coordinates-in-swift

Goal is to not build a custom list of map providers because maybe user users a completely custom navigator app like Sygic. System is usually smart enough to find all possible navigation options.

**Comment by mattermoran** [comment]
Hi @AAverin 
If you want to trigger default android map picker, you can just use `geo://` url with `url_launcher` plugin. Though it does not work the same way on ios and there you have to specify custom url for different maps. The link you provided does not seem to mention anything about opening a maps picker on ios but only how to open apple maps. This plugin already allows you to do that. Let me know if I missed something there.

The `geo://` url is more universal on android but it's very limited and does not let you specify custom parameters that some maps support like zoom levels, marker titles and descriptions, custom origin points and direction modes for navigation, etc. When using `geo://` url developer also does not know what map user is going to use and cannot adjust coords to a different coordinate system that sometimes needed for Chinese maps.
This plugin is there to help with that stuff.

It might be useful to add support for `geo://` url that would show native map picker on android and just open Apple Maps on ios. Not sure what api would look like, probably something like `launchMap(MapType.Any)` or `launchMap(MapType.Geo)`. 
Feel free to send a PR if you have ideas.

**Comment by mattermoran** [comment]
As mentioned in my previous comment `geo:` can be used directly with `url_launcher` and support for this in this plugin is not planned.
