### ISSUE TITLE
Rename "Apple Maps" into "Apple Plans"

### ISSUE THREAD

**Issue by subnauez** [mattermoran/map_launcher#37]
It seems that "Apple Maps" is not the correct name.
This one should be renamed into "Apple Plans". 

Could you change this please ?

**Comment by mattermoran** [comment]
ummm what? Since when is it called apple plans?

**Comment by subnauez** [comment]
It's maybe only a translation issue ... 
On our region, we don't use "Apple Maps" but "Apple Plans"...

FYI, we used your plugin on a testing app. 
Some users noticed that this app name is not correct.
So we need to change it. 

Is there any way to override the name associated to an app ? 
Or do we need to fork the project for modifying this ?

Thank you for your feedback.
Best regards.

**Comment by mattermoran** [comment]
Interesting. Well in that case you should do the translation on your side. I assume currently you are using `.mapName` property that gives you English name so you could either translate that or better rely on `.mapType` property and provide your own translation
