### ISSUE TITLE
Google Maps zoom level not set by default on iOS

### ISSUE THREAD

**Issue by aseef17** [mattermoran/map_launcher#39]
Currently, the zoom has to be set manually for GMaps to function correctly on an iOS device. 
If zoom is not set (which should default to 16 according to docs), the world map is displayed on GMaps instead of zooming in on the desired location.

The easy fix for this is just to set the zoom level but this should be enabled by default I assume.

**Comment by mattermoran** [comment]
I actually thought I had it working but looks like I forgot that dart is not using default parameter is null is being passed. Fixed in  0.12.1
