### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by melih1996** [mattermoran/map_launcher#40]
Hi, when I import the library it gives the error below :
Compiler message:
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/svg.dart:741:13: Error: No named parameter with the name 'clipBehavior'.
            clipBehavior: widget.clipBehavior,
            ^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/basic.dart:1410:9: Context: Found this candidate, but the arguments don't match.
  const FittedBox({

**Comment by mattermoran** [comment]
I think the correct version for flutter_svg is not being resolved. What version of flutter are you using? Does this error happen when you first time import this plugin or after you upgraded flutter?

**Comment by wizawuza** [comment]
Not to thread hijack, but I got a similar error so I figure I'd post what caused it for me:
Compiler message:
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^


flutter version: flutter 1.20.4 • channel stable
I did not recently upgrade flutter, but I did just installed map_launcher

**Comment by wizawuza** [comment]
Not sure if it's a good fix, but I just installed this dependency and it works:
`flutter_svg: ^0.18.0`

**Comment by mattermoran** [comment]
Should not be an issue in version 1.0 anymore as it does not depend on flutter_svg
