### ISSUE TITLE
Feature request: Korean Maps(kakao, naver,...)

### ISSUE THREAD

**Issue by ericel** [mattermoran/map_launcher#42]
Any plans to add more maps.
Like Korean Maps(kakao, naver,...)

**Comment by mattermoran** [comment]
Hey. You could contribute and add support for missing maps that you need. You can see an example here: https://github.com/mattermoran/map_launcher/pull/25
I might add them in future releases when I have more time

**Comment by mattermoran** [comment]
Hi @ericel 
if you can provide documentation for those maps you want I could look at that in my free time

**Comment by mattermoran** [comment]
The progress will be tracked here https://github.com/mattermoran/map_launcher/issues/111
