### ISSUE TITLE
Error on IOS

### ISSUE THREAD

**Issue by dmanzanomartin** [mattermoran/map_launcher#43]
Hi, when I use the google map with waypoints, on IOS it starts the google maps app, but doesn't set the destination and I have to add it manually, does anybody knows how can I do for the app do it alone? The same code works perfectly on Android.

Thanks.

**Comment by mattermoran** [comment]
I have just tested on iOS and I don't seem to have any issues with waypoints. Can you try the example app in /example folder and see if it works for you? Can you post screenshots or videos?

**Comment by dmanzanomartin** [comment]
> I have just tested on iOS and I don't seem to have any issues with waypoints. Can you try the example app in /example folder and see if it works for you? Can you post screenshots or videos?

I did a flutter clear and works perfectly, thank you so much. Nice plugin, keep doing same 👍

**Comment by dmanzanomartin** [comment]
It's still not working, when I open it give me this:
![IMG_5090](https://user-images.githubusercontent.com/44710339/97235030-4c97da00-17e2-11eb-9ea6-4e030c3b9b28.PNG)

And if I have markers I can continue, but if I don't have I can't.

**Comment by mattermoran** [comment]
I see what you are saying now. Looks like Google Maps for ios have a limit of max 8 waypoints: https://stackoverflow.com/questions/40089130/is-there-any-limits-of-waypoints-to-draw-a-route-in-google-map-for-ios

Not much I can do here, sorry :(

**Comment by mattermoran** [comment]
Added info in README that ios only supports up to 8 waypoints
