### ISSUE TITLE
Can not open on Nokia 1 

### ISSUE THREAD

**Issue by lcc728** [mattermoran/map_launcher#44]
Hi,
   I can't open map on Nokia 1( Maps GO), when I try to use print(availableMaps), I got this message on terminal: **I/flutter (16191): []**
   Thanks.

**Comment by mattermoran** [comment]
Hi. I assume you only have one map installed that is not supported by this plugin. Is it google maps go? I will check and add it for the next release

**Comment by lcc728** [comment]
Yes, I only have on map that is Google Maps GO, 
Thanks.

**Comment by mattermoran** [comment]
It's been added in https://github.com/mattermoran/map_launcher/pull/48 by @andoni97 and now available in version 1.0.0
