### ISSUE TITLE
Error: Type 'DiagnosticableMixin' not found. class DateTimePickerTheme with DiagnosticableMixin 

### ISSUE THREAD

**Issue by mjl1564159881** [mattermoran/map_launcher#45]
https://github.com/dylanwuzh/flutter-cupertino-date-picker/issues/126

This may need to be solved by you

thank  you very much

**Comment by mattermoran** [comment]
hey, thanks! I'm aware of this issue that's being caused by flutter_svg. I'm about to release a new version with a breaking change where this plugin will not depend on flutter_svg and if users can use whatever version of flutter_svg they want :)

**Comment by mattermoran** [comment]
Should not be an issue in version 1.0 anymore as it does not depend on flutter_svg
