### ISSUE TITLE
navigator requre sign

### ISSUE THREAD

**Issue by TheLexI** [mattermoran/map_launcher#52]
Yndex navigator requre key: https://yandex.ru/dev/yandex-apps-launch/navigator/doc/concepts/navigator-commercial-use-signature.html/
how do I use this library to meet these requirements?

**Comment by mattermoran** [comment]
Hi @TheLexI 
Unfortunately, this plugin does not support passing client and signature params. It's not something I can test as it requires getting some kind of an access key.
Feel free to send a PR

**Comment by mattermoran** [comment]
Hi @TheLexI 
Version 1.1.1 now supports passing `extraParams` options with any additional query params required so you should be able to use it for Yandex Navigator like so:
```dart
map.showMarker(
  coords: coords,
  title: title,
  extraParams: {
    'client': '', 
    'signature': ''
  }
),
```
