### ISSUE TITLE
iOS Tencent config error

### ISSUE THREAD

**Issue by fei-sheng** [mattermoran/map_launcher#56]
Map(mapName: "Tencent (QQ Maps)", mapType: MapType.tencent, urlPrefix: "qqmap://"),
Map(mapName: "2GIS", mapType: MapType.doubleGis, urlPrefix: "dgis://")

**Comment by mattermoran** [comment]
oh my bad. I'll push a fix soon

**Comment by mattermoran** [comment]
fixed in https://github.com/mattermoran/map_launcher/commit/4a008111760ee40252ce3994a183ad226c05c309 and available in version 1.1.2
