### ISSUE TITLE
zh_en

### ISSUE THREAD

**Issue by ITmxs** [mattermoran/map_launcher#59]
希望可以提供国际化支持

**Comment by ITmxs** [comment]
for example  Amap--高德地图

**Comment by mattermoran** [comment]
at the moment there's no support for languages other than English but for now you could add a helper method in your code something like this:

```dart
String getMapName(AvailableMap map) {
    switch (map.mapType) {
        case MapType.amap:
            return '高德地图'
        ...
        default:
            return map.mapName
    }
}
```

**Comment by ITmxs** [comment]
> at the moment there's no support for languages other than English but for now you could add a helper method in your code something like this:
> 
> ```dart
> String getMapName(AvailableMap map) {
>     switch (map.mapType) {
>         case MapType.amap:
>             return '高德地图'
>         ...
>         default:
>             return map.mapName
>     }
> }
> ```


Where should i add**import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
  static show({
    @required BuildContext context,
    @required Function(AvailableMap map) onMapTap,
  }) async {
    final availableMaps = await MapLauncher.installedMaps;

    showModalBottomSheet(
      context: context,
      builder: (BuildContext context) {
        return SafeArea(
          child: Column(
            children: <Widget>[
              Expanded(
                child: SingleChildScrollView(
                  child: Container(
                    child: Wrap(
                      children: <Widget>[
                        for (var map in availableMaps)
                          ListTile(
                            onTap: () => onMapTap(map),
                            title: Text(map.mapName),
                            leading: SvgPicture.asset(
                              map.icon,
                              height: 30.0,
                              width: 30.0,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
**

**Comment by ITmxs** [comment]
where shou i add?


**import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
  static show({
    @required BuildContext context,
    @required Function(AvailableMap map) onMapTap,
  }) async {
    final availableMaps = await MapLauncher.installedMaps;

    showModalBottomSheet(
      context: context,
      builder: (BuildContext context) {
        return SafeArea(
          child: Column(
            children: <Widget>[
              Expanded(
                child: SingleChildScrollView(
                  child: Container(
                    child: Wrap(
                      children: <Widget>[
                        for (var map in availableMaps)
                          ListTile(
                            onTap: () => onMapTap(map),
                            title: Text(map.mapName),
                            leading: SvgPicture.asset(
                              map.icon,
                              height: 30.0,
                              width: 30.0,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
**

**Comment by ITmxs** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
static show({
@required BuildContext context,
@required Function(AvailableMap map) onMapTap,
}) async {
final availableMaps = await MapLauncher.installedMaps;

showModalBottomSheet(
  context: context,
  builder: (BuildContext context) {
    return SafeArea(
      child: Column(
        children: <Widget>[
          Expanded(
            child: SingleChildScrollView(
              child: Container(
                child: Wrap(
                  children: <Widget>[
                    for (var map in availableMaps)
                      ListTile(
                        onTap: () => onMapTap(map),
                        title: Text(map.mapName),
                        leading: SvgPicture.asset(
                          map.icon,
                          height: 30.0,
                          width: 30.0,
                        ),
                      ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  },
);
}
}

**Comment by ITmxs** [comment]
where should i add ?
`import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
static show({
@required BuildContext context,
@required Function(AvailableMap map) onMapTap,
}) async {
final availableMaps = await MapLauncher.installedMaps;

showModalBottomSheet(
  context: context,
  builder: (BuildContext context) {
    return SafeArea(
      child: Column(
        children: <Widget>[
          Expanded(
            child: SingleChildScrollView(
              child: Container(
                child: Wrap(
                  children: <Widget>[
                    for (var map in availableMaps)
                      ListTile(
                        onTap: () => onMapTap(map),
                        title: Text(map.mapName),
                        leading: SvgPicture.asset(
                          map.icon,
                          height: 30.0,
                          width: 30.0,
                        ),
                      ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  },
);
}
}`

**Comment by ITmxs** [comment]
> at the moment there's no support for languages other than English but for now you could add a helper method in your code something like this:
> 
> ```dart
> String getMapName(AvailableMap map) {
>     switch (map.mapType) {
>         case MapType.amap:
>             return '高德地图'
>         ...
>         default:
>             return map.mapName
>     }
> }
> ```

where should i  add ?

**Comment by ITmxs** [comment]
> at the moment there's no support for languages other than English but for now you could add a helper method in your code something like this:
> 
> ```dart
> String getMapName(AvailableMap map) {
>     switch (map.mapType) {
>         case MapType.amap:
>             return '高德地图'
>         ...
>         default:
>             return map.mapName
>     }
> }
> ```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
static show({
@required BuildContext context,
@required Function(AvailableMap map) onMapTap,
}) async {
final availableMaps = await MapLauncher.installedMaps;

showModalBottomSheet(
  context: context,
  builder: (BuildContext context) {
    return SafeArea(
      child: Column(
        children: <Widget>[
          Expanded(
            child: SingleChildScrollView(
              child: Container(
                child: Wrap(
                  children: <Widget>[
                    for (var map in availableMaps)
                      ListTile(
                        onTap: () => onMapTap(map),
                        title: Text(map.mapName),
                        leading: SvgPicture.asset(
                          map.icon,
                          height: 30.0,
                          width: 30.0,
                        ),
                      ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  },
);
}
}

**Comment by mattermoran** [comment]
First add the getMapName method somewhere in your code. then use it like this:
```dart
for (var map in availableMaps)
  ListTile(
    onTap: () => onMapTap(map),
    title: Text(getMapName(map)), // HERE
    leading: SvgPicture.asset(
      map.icon,
      height: 30.0,
      width: 30.0,
    ),
  ),
```

**Comment by ITmxs** [comment]
thank you hope the future can be added to example------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Alex&amp;nbsp;Miller&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月1日(星期一) 下午3:01
收件人:&nbsp;&quot;mattermoran/map_launcher&quot;<map_launcher@noreply.github.com&gt;;
抄送:&nbsp;&quot;ITmxs&quot;<852851198@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mattermoran/map_launcher] zh_en (#59)

**Comment by ITmxs** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
  BuildContext context;
  Function(AvailableMap map) onMapTap;
  MapsSheet({this.context, this.onMapTap});

  void show() async {
    List<AvailableMap> availableMaps = await MapLauncher.installedMaps;
    for (var map in availableMaps) {
      map.mapName = getLocalName(amap: map);
    }

    showModalBottomSheet(
      // backgroundColor: Colors.transparent,
      context: context,

      builder: (BuildContext context) {
        return Container(
          padding: EdgeInsets.only(left: 10),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.all(Radius.circular(20)),
          ),
          height: 400,
          child: Column(
            children: <Widget>[
              Expanded(
                child: SingleChildScrollView(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.all(Radius.circular(16)),
                    ),
                    child: Wrap(
                      children: <Widget>[
                        for (var map in availableMaps)
                          ListTile(
                            onTap: () => onMapTap(map),
                            title: Text(map.mapName),
                            leading: SvgPicture.asset(
                              map.icon,
                              height: 30.0,
                              width: 30.0,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  String getLocalName({AvailableMap amap}) {
    switch (amap.mapType) {
      case MapType.amap:
        return '高德地图';

      case MapType.baidu:
        return '百度地图';
      case MapType.tencent:
        return '腾讯地图';
      case MapType.google:
        return '谷歌地图';

      default:
        return amap.mapName;
    }
  }
}
  `###``

**Comment by ITmxs** [comment]
I think you should use an
`<import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
  BuildContext context;
  Function(AvailableMap map) onMapTap;
  MapsSheet({this.context, this.onMapTap});

  void show() async {
    List<AvailableMap> availableMaps = await MapLauncher.installedMaps;
    for (var map in availableMaps) {
      map.mapName = getLocalName(amap: map);
    }

    showModalBottomSheet(
      // backgroundColor: Colors.transparent,
      context: context,

      builder: (BuildContext context) {
        return Container(
          padding: EdgeInsets.only(left: 10),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.all(Radius.circular(20)),
          ),
          height: 400,
          child: Column(
            children: <Widget>[
              Expanded(
                child: SingleChildScrollView(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.all(Radius.circular(16)),
                    ),
                    child: Wrap(
                      children: <Widget>[
                        for (var map in availableMaps)
                          ListTile(
                            onTap: () => onMapTap(map),
                            title: Text(map.mapName),
                            leading: SvgPicture.asset(
                              map.icon,
                              height: 30.0,
                              width: 30.0,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  String getLocalName({AvailableMap amap}) {
    switch (amap.mapType) {
      case MapType.amap:
        return '高德地图';

      case MapType.baidu:
        return '百度地图';
      case MapType.tencent:
        return '腾讯地图';
      case MapType.google:
        return '谷歌地图';

      default:
        return amap.mapName;
    }
  }
}
>`
