### ISSUE TITLE
Add yandex navigator

### ISSUE THREAD

**Issue by RakhimyanTim** [mattermoran/map_launcher#6]
Hi! great job! 
If you can add pls [yandex navigator](https://play.google.com/store/apps/details?id=ru.yandex.yandexnavi&hl=en_US) (maps).

**Comment by mattermoran** [comment]
Thanks!
Will be added in the next release

**Comment by RakhimyanTim** [comment]
Sounds interesting! thanks!

**Comment by mattermoran** [comment]
@RakhimyanTim version 0.4.0 with yandex maps and navigator is now available on pub
