### ISSUE TITLE
How to pass and retrieve data from firebase 

### ISSUE THREAD

**Issue by zakblacki** [mattermoran/map_launcher#61]
I'd like to retrieve some value from firebase 
say for example a "cafe shop" location 
how do I pass the argument with this 

        final dbRef = FirebaseDatabase.instance.reference().child("cafe");

        body: StreamBuilder(
        stream: dbRef.onValue,
        builder: (context, AsyncSnapshot<Event> snapshot) {
         if (snapshot.hasData) {
         lists.clear();
         DataSnapshot dataValues = snapshot.data.snapshot;
         Map<dynamic, dynamic> values = dataValues.value;
         values.forEach((key, values) {
            lists.add(values);
        });

**Comment by mattermoran** [comment]
I'm not sure what your cafe objects look like but if they have coordinates you could pass them kind of like this
```dart
await MapLauncher.showMarker(
    mapType: MapType.google,
    coords: Coords(cafe.latitude, cafe.longitude),
    title: title,
    description: description,
  );
```
