### ISSUE TITLE
Package key missing 

### ISSUE THREAD

**Issue by muhammednazil** [mattermoran/map_launcher#65]
Launching lib\main.dart on SM G973F in debug mode...
Running Gradle task 'assembleDebug'...
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:5:9-64 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:5:9-64
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:6:9-68 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:6:9-68
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:7:9-56 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:7:9-56
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:8:9-54 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:8:9-54
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:9:9-44 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:9:9-44
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:10:9-56 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:10:9-56
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:11:9-56 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:11:9-56
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:12:9-62 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:12:9-62
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:13:9-59 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:13:9-59
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:14:9-46 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:14:9-46
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:15:9-57 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:15:9-57
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml:16:9-51 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:16:9-51
C:\Users\naazi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\map_launcher-1.1.3+1\android\src\main\AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':map_launcher:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Manifest merger failed with multiple errors, see logs

**Comment by muhammednazil** [comment]
Anyone please help me

**Comment by mattermoran** [comment]
Solution is here https://github.com/mattermoran/map_launcher/issues/60#issuecomment-771388357

**Comment by mattermoran** [comment]
@muhammednazil let me know if that worked for you

**Comment by BasedMusa** [comment]
I'm on Gradle 4.3.3, what should I upgrade to?

I've got this same issue.

**Comment by mattermoran** [comment]
@BasedMusa you must be looking in the wrong place. based on [this](https://developer.android.com/studio/releases/gradle-plugin) it seems like the latest gradle version is 4.1.*. Make sure you looking in the correct file

**Comment by BasedMusa** [comment]
Nevermind, I was actually on 3.5.0, the 4.3.3 value was my google services plugin version.

**Comment by mattermoran** [comment]
Glad it worked out

**Comment by muhammednazil** [comment]
Thank you
