### ISSUE TITLE
Yandex destination and origin is wrong

### ISSUE THREAD

**Issue by mrxten** [mattermoran/map_launcher#68]
If I dont specify origin for Yandex, then destination set up as origin in map

**Comment by mattermoran** [comment]
Just re-checked the documentation and it seems that origin is required and it won't work without it for Yandex maps. [docs](https://yandex.com/dev/yandex-apps-launch/maps/doc/concepts/yandexmaps-ios-app.html#yandexmaps-ios-app__buildroute)

For now, you could get the user location in flutter and pass it to `origin` or if there's no location, call `showMarker` instead.

I might handle this in `showDirections` method where it would check for maps that have origin required it would just launch with marker

**Comment by mrxten** [comment]
Ok, thanks5 апр. 2021 г. 11:40 пользователь Alex Miller ***@***.***> написал:
Just re-checked the documentation and it seems that origin is required and it won't work without it for Yandex maps. docs
For now, you could get the user location in flutter and pass it to origin or if there's no location, call showMarker instead.
I might handle this in showDirections method where it would check for maps that have origin required it would just launch with marker
