### ISSUE TITLE
MissingPluginException(No implementation found for method isMapAvailable on channel map_launcher)

### ISSUE THREAD

**Issue by emreyalcinnetcad** [mattermoran/map_launcher#7]
MissingPluginException(No implementation found for method isMapAvailable on channel map_launcher)

**Comment by mattermoran** [comment]
Hi. Could you provide more details like plugin version, flutter version and a device you running it on? Output from flutter doctor would be helpful as well

**Comment by emreyalcinnetcad** [comment]
I found the error. i added google_maps_flutter under the dev_dependencies . I moved it to dependencies. Thank you for your great package
