### ISSUE TITLE
Redirect to calling app on destination reach

### ISSUE THREAD

**Issue by premy** [mattermoran/map_launcher#70]
Hi, nice package, thank u. Do you plan to add the ability to redirect to the calling app when destination is reached on the Google Maps app (or waze), much like Uber?

**Comment by mattermoran** [comment]
hmm, I haven't used that in Uber so not sure how did they implement it but the only way I can imagine (except for some hacks on Android) is to create a geofence around destination and do something when it gets triggered. But that's something you could do in your own app and completely out of scope for this plugin (at least at the moment)
