### ISSUE TITLE
Add multiple Marker

### ISSUE THREAD

**Issue by mstfkhazaal** [mattermoran/map_launcher#74]
How can add multiple maker

**Comment by mattermoran** [comment]
You can't. Well, not with this plugin at least. As far as I know, maps don't support that with a URL scheme. The only one that might support it is Apple Maps but it's not implemented. I don't even know where would it be needed to show multiple markers on the external map. What is your usecase?
What you probably looking for is something like google_maps_flutter plugin or flutter_map. You embed a map within your app and can add as many markers, overlays, etc, as you want

**Comment by mstfkhazaal** [comment]
Thanks
