### ISSUE TITLE
Provide Departure time or Arrival time on opening Map Application

### ISSUE THREAD

**Issue by Yooooomi** [mattermoran/map_launcher#75]
Hello!

Is there a way to provide a departure or arrival time when opening the maps applications ? Something like:
```dart
app.showDirections(
          origin: origin?.coords,
          originTitle: origin?.title,
          destination: destination.coords,
          destinationTitle: destination.title,
          departureTime: DateTime.now().add(Duration(hours: 1)),
        );
```

Thanks for your answer

**Comment by mattermoran** [comment]
Hi. Sorry for the late reply.
I don't really know if maps support this. If you have a link for some maps documentation with this feature I can take a look

**Comment by mattermoran** [comment]
Doesn't look like maps support this feature so this is not something this plugin can do.
Reopen, if you know maps that actually support it and if possible provide link to the docs :)
