### ISSUE TITLE
Why Google Maps is opened without title on Android?

### ISSUE THREAD

**Issue by tomk9** [mattermoran/map_launcher#8]
Why map url on Android doesn't contain `title`?
```dart
case MapType.google:
      if (Platform.isIOS) {
        return 'comgooglemaps://?q=$title&center=${coords.latitude},${coords.longitude}';
      }
      return 'geo:${coords.latitude},${coords.longitude}?q=${coords.latitude},${coords.longitude}';
```
It causes differences in the map display.

| iOS | Android |
| :---: | :---: |
| ![IMG_0012 1](https://user-images.githubusercontent.com/15803067/72885008-5fd3c180-3d07-11ea-97d0-f46e6572c3e1.PNG) | ![Screenshot_20200122-105726](https://user-images.githubusercontent.com/15803067/72885087-898ce880-3d07-11ea-88a0-937fd183c97d.png) |

**Comment by mattermoran** [comment]
Hi.
Official documentation says that the custom label can be added after latlong like  ```...q=lat,long(custom label)```
![image](https://user-images.githubusercontent.com/29712386/72888041-c7116600-3d47-11ea-9460-b6e05fe269cb.png)

But last time I checked it wasn't working and looks like it's still an issue today.
You can read more about it on [StackOverflow](https://stackoverflow.com/questions/55078219/geo-intent-label-not-showing-in-google-maps-app) or [Google Issue Tracker](https://issuetracker.google.com/issues/129726279)

But I think I should still add it in code so once google fixes the app it will just work.

**Comment by mattermoran** [comment]
Version 0.4.2 has code to show label on Android but it will only work once Google Maps team fixes it on their side as well.

**Comment by mattermoran** [comment]
iOS should have a title now. For Android nothing we can do until Google Maps team fixes it

**Comment by darmawan01** [comment]
Work on me, just add extra params 😄 

```
extraParams: {'q': '($title)'}
```
