### ISSUE TITLE
OSMAnd+ is not properly identified on Android

### ISSUE THREAD

**Issue by bridystone** [mattermoran/map_launcher#80]
OSMAnd is not recognized as available on Android. 
Even though installed, it is not added to the availableMaps

**Comment by mattermoran** [comment]
That's strange. It was definitely working when was added (been a while ago)
It's possible that URL scheme has been changed in the new version of osmand so it doesn't recognize it now.
I'll try to find some time tomorrow to see what's happening.
P.S. thanks for PRs I'll check them tomorrow as well and merge :)

**Comment by bridystone** [comment]
I've found an issue - at least on my device

the correct packageid is: "net.osmand.plus" - not "net.osmand" ... maybe this has changed
I've checked in the OSMAND repo. the Manifest uses the packageid with "plus"

I've also checked this with my phone with your code and the adjusted packageID and it worked

**Comment by bridystone** [comment]
I'm not familiar with kotlin.
if there are different package ids (i.e. net.osmand.plus & net.osmand.dev) can you add this to one MAP? I guess it is not easily doable, because the enum is the primary key here - right?

**Comment by bridystone** [comment]
i've just checked in the emulator. Even in the playstore there are 2 different versions of OSMAnd available.
net.osmand.plus & net.osmand
So my "fix" would break also something.

net.osmand is the default playstore version.
net.osmand.plus is
- playstore "plus" version
- apk installation from their website
- own build / fdroid version

The easiest way to fix this might be to add a new enum in the list - so one needs to check for OSMAnd & OSMAndPlus.
Otherwise it might get a little messy and some changes might be required....

**Comment by mattermoran** [comment]
oh, I see. In this case, yes, the best way is to add it as a separate app with a different name and an icon. It seems that osmand+ only available on Android so it's similar to Google Maps Go

**Comment by bridystone** [comment]
i've updated the pull request accordingly:)

**Comment by mattermoran** [comment]
Version 2.1.0 is OSMAnd+ is not available on pub. Thanks @bridystone
