### ISSUE TITLE
Version 2.2.1 reports requires IOS 10.0

### ISSUE THREAD

**Issue by 4bSolutionsLLP** [mattermoran/map_launcher#88]
After updating to version 2.2.1, builds ok but get link errors reporting that minimum IOS version must be 10.0. whilst you can change this in Xcode and compile, each time you build, it reverts to IOS 9 and  fails.

**Comment by mattermoran** [comment]
Yes, the minimum version has been increased to 10.
This means you need to set iOS version in deployment info to 10 and higher. E.g this is the example project:
![image](https://user-images.githubusercontent.com/29712386/124072971-121ec500-da74-11eb-8171-d18f5030d785.png)

Do you mean you did this change but it keeps going back to 9?

**Comment by mattermoran** [comment]
Also if you have an iOS version set in your Podfile you will also need to update that as well
```
platform :ios, '10.0'
```

**Comment by 4bSolutionsLLP** [comment]
> Yes, the minimum version has been increased to 10.
> This means you need to set iOS version in deployment info to 10 and higher. E.g this is the example project:
> ![image](https://user-images.githubusercontent.com/29712386/124072971-121ec500-da74-11eb-8171-d18f5030d785.png)
> 
> Do you mean you did this change but it keeps going back to 9?

Yes exactly.

In XCode, PROJECT -> Runner: Deployment -> IOS Deployment Target is set to IOS 10.0 and is not the issue.
However, if I go to Pods in XCode -> TARGETS and select the "map_launcher" entry, it shows under Deployment, IOS Deployment Target: IOS 9.0 and gives reported error. If i change this entry to IOS 10.0 it temporarily solves the issue but as soon as I re-build in Android Studio, this gets reset back to IOS 9.0.

**Comment by 4bSolutionsLLP** [comment]
> > Yes, the minimum version has been increased to 10.
> > This means you need to set iOS version in deployment info to 10 and higher. E.g this is the example project:
> > ![image](https://user-images.githubusercontent.com/29712386/124072971-121ec500-da74-11eb-8171-d18f5030d785.png)
> > Do you mean you did this change but it keeps going back to 9?
> 
> Yes exactly.
> 
> In XCode, PROJECT -> Runner: Deployment -> IOS Deployment Target is set to IOS 10.0 and is not the issue.
> However, if I go to Pods in XCode -> TARGETS and select the "map_launcher" entry, it shows under Deployment, IOS Deployment Target: IOS 9.0 and gives reported error. If i change this entry to IOS 10.0 it temporarily solves the issue but as soon as I re-build in Android Studio, this gets reset back to IOS 9.0.

Here is a screenshot re my previous comments...
![Screenshot](https://user-images.githubusercontent.com/67598738/124080597-745ed200-da42-11eb-911f-e579f289c2da.png)

**Comment by mattermoran** [comment]
You should not manually adjust the ios version in the pods. Just make sure your Podfile under /ios folder has ios version set to 10
Let me know if that still doesn't help. Also, make sure to run flutter clean so there's no caching

**Comment by 4bSolutionsLLP** [comment]
> You should not manually adjust the ios version in the pods. Just make sure your Podfile under /ios folder has ios version set to 10
> Let me know if that still doesn't help. Also, make sure to run flutter clean so there's no caching

Thanks - that makes sense. I'm pretty new to Flutter - are you talking about a file accessed from Xcode or from Android Studio? Can you point me towards which file exactly and where it is? Many thanks for your help.

**Comment by mattermoran** [comment]
You can access it either way. It's in your project's ios folder. Here's what it looks like in VSCode:
![image](https://user-images.githubusercontent.com/29712386/124081362-06d09700-da7e-11eb-97be-c61f2e36c988.png)

Or this is in Xcode:
![image](https://user-images.githubusercontent.com/29712386/124081399-15b74980-da7e-11eb-840f-7f94c4fbdb4d.png)

On line 2 you can uncomment (if you haven't already) and set correct version
![image](https://user-images.githubusercontent.com/29712386/124081534-40090700-da7e-11eb-8287-f8cd9a110686.png)

**Comment by 4bSolutionsLLP** [comment]
Thanks so much for your patience and for walking me through this. I also found an entry in the Podfile which expressly set config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0' and I also needed to change 9.0 to 10.0.

Seems to be working now!

**Comment by mattermoran** [comment]
Perfect, no problem, glad it worked out for you :)
