### ISSUE TITLE
Swift link errors??

### ISSUE THREAD

**Issue by rgbinnovation** [mattermoran/map_launcher#89]
Hi all, getting a ton of Swift linking errors when I add this package:

ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftMapKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreAudio'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftCoreLocation'
ld: warning: Could not find or use auto-linked library 'swiftCoreMedia'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'

Refuses to build. Has anyone come across a solution to this? Googles and tried to add LD_VERIFY_BITCODE = NO but didn't work.

**Comment by mattermoran** [comment]
you seem to have the same issue as #49.  do you have an old project that is based on obj c?
the solution is there in the comments as well: https://github.com/mattermoran/map_launcher/issues/49#issuecomment-727121619

let me know if that doesn't help you

**Comment by rgbinnovation** [comment]
Hi Matt, you were right. Seems the project was old and not upgraded to Swift. All works correctly now, thanks for providing the link to instructions on how to upgrade. Appreciate I!

**Comment by mattermoran** [comment]
Glad it works for you now :)
