### ISSUE TITLE
'Restore Apple maps' pop up twice when Apple maps is not installed on device.

### ISSUE THREAD

**Issue by alvindrakes** [mattermoran/map_launcher#91]
When Apple maps is not installed on the device and the map_launcher is trying to open it, the 'restore Apple maps' pop up will appear twice in a row. 

is this intended? 

![image](https://user-images.githubusercontent.com/13532268/129078860-596372f5-314b-41a4-ae52-bd20f6f27aab.png)

**Comment by daivph** [comment]
me too

**Comment by e-papa** [comment]
Might be related to https://developer.apple.com/forums/thread/127960 ?

**Comment by mattermoran** [comment]
Seems to be a bug on the apple side when calling `MKMapItem.openInMaps`.  There still doesn't seem to be a way to check if apple maps have been removed or not so no way to work around this :(
