### ISSUE TITLE
Starting in popup view

### ISSUE THREAD

**Issue by mohammedX6** [mattermoran/map_launcher#95]
I want to launch the google maps app in popup mode, on supported devices only, How I can achieve that?

**Comment by mattermoran** [comment]
can you show an example of that popup mode? I'm not sure if I've seen it before

**Comment by mohammedX6** [comment]
Yes sure
![maps-pip-w596](https://user-images.githubusercontent.com/24648104/144748621-97141df8-6ee3-4d8a-a217-3ce5c669570f.jpeg)
e

**Comment by mattermoran** [comment]
This just seems to be a google maps feature and I think it should work the same way if you call `showDirections` and then select a route, no?
Or if there actually apps that open in that popup mode right away?

**Comment by mattermoran** [comment]
Closing this as this is just a google maps specific feature on android, has nothing to do with this plugin.
If you think there's a way to actually toggle picture in picture mode from url scheme let me know :)
