### ISSUE TITLE
Coords issue

### ISSUE THREAD

**Issue by Lawati97** [mattermoran/map_launcher#97]
Whenever i want to use the package I get this error that am not certain how to fix

The name 'Coords' is defined in the libraries 'package:flutter_map/src/layer/tile_layer.dart (via package:flutter_map/flutter_map.dart)' and 'package:map_launcher/src/models.dart (via package:map_launcher/map_launcher.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.dartambiguous_import
'Coords' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'Coords'.dartinvocation_of_non_function
The argument type 'dynamic' can't be assigned to the parameter type 'Coords'.dartargument_type_not_assignable

this is where I use it:

map.showDirections(
                              destination: Coords(
                                lat,
                                long,
                              ),
)

using flutter 2.5.3

**Comment by mattermoran** [comment]
Sorry, I must've missed this message.
As the error message suggests try prefixing map launcher on import like `import 'package:map_launcher/map_launcher.dart' as ml;`. then you can use Coords like `ml.Coords(...`
